### ISSUE TITLE
SPMC Log Uploader Error

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#107]
Error when trying to upload log.

`12:22:13 T:1455188272   ERROR: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/data/user/0/com.semperpax.spmc16/cache/apk/assets/addons/script.xbmc.debug.log/addon.py", line 198, in <module>
                                                Uploader = LogUploader()
                                              File "/data/user/0/com.semperpax.spmc16/cache/apk/assets/addons/script.xbmc.debug.log/addon.py", line 58, in __init__
                                                self.report_mail(self.email_address, uploaded_logs)
                                              File "/data/user/0/com.semperpax.spmc16/cache/apk/assets/addons/script.xbmc.debug.log/addon.py", line 129, in report_mail
                                                response = urllib2.urlopen(req).read()
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 397, in open
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 510, in http_response
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 435, in error
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 518, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
12:22:34 T:1394157872  NOTICE: NFS is idle. Closing the remaining connections.`

Log: http://pastebin.com/PACpkD7T

**Comment by ghost** [comment]
Can also confirm this is an issue using 16.1.1.

**Comment by koying** [comment]
As a matter of fact, logs are uploaded.
It's the "emailing" part which is failing...

**Comment by koying** [comment]
Will revert to using xbmclogs.
It appears it doesn't belong to the kodi foundation, so I won't use their resources
