### ISSUE TITLE
Subtitle addons not working

### ISSUE THREAD

**Issue by babaloui** [koying/SPMC#210]
SPMC Version 16.2.0 (nVidia Shield)

20:43:21 T:1537202480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe5' in position 14: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.opensubtitles/service.py", line 154, in <module>
                                                lan = xbmc.convertLanguage(lang,xbmc.ISO_639_2)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 14: ordinal not in range(128)
                                            -->End of Python script error report<--
20:43:21 T:1397250352   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://service.subtitles.opensubtitles/?action=search&languages=English%2cNorwegian%20Bokm%c3%a5l&preferredlanguage=English
20:43:24 T:1537202480   ERROR: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.podnapisi/resources/lib/pn_utilities.py:103: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              if lang == x[lang_from] :
20:43:24 T:1537202480   ERROR: Error loading addon settings to special://profile/addon_data/service.subtitles.podnapisi/settings.xml
20:43:24 T:1537202480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: sequence item 1: expected string, NoneType found
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.podnapisi/service.py", line 178, in <module>
                                                Search(item)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.podnapisi/service.py", line 44, in Search
                                                subtitles_list = pn_server.SearchSubtitlesWeb(item)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.podnapisi/resources/lib/pn_utilities.py", line 276, in SearchSubtitlesWeb
                                                ','.join(item['3let_language']),
                                            TypeError: sequence item 1: expected string, NoneType found
                                            -->End of Python script error report<--
20:43:24 T:1444919600   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://service.subtitles.podnapisi/?action=search&languages=English%2cNorwegian%20Bokm%c3%a5l&preferredlanguage=English
20:43:26 T:1537202480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe5' in position 14: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.subscene/service.py", line 508, in <module>
                                                item['3let_language'].append(xbmc.convertLanguage(lang, xbmc.ISO_639_2))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 14: ordinal not in range(128)
                                            -->End of Python script error report<--
20:43:26 T:1453193520   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://service.subtitles.subscene/?action=search&languages=English%2cNorwegian%20Bokm%c3%a5l&preferredlanguage=English
20:43:28 T:1387866416  NOTICE: CEGLNativeTypeAndroid: Current resolution: 1920x1080 @ 23.976025 - Full Screen
20:44:24 T:1387866416   ERROR: Error loading addon settings to special://profile/addon_data/service.subtitles.opensubtitles/settings.xml
20:44:35 T:1387866416   ERROR: Error loading addon settings to special://profile/addon_data/service.subtitles.podnapisi/settings.xml
20:44:40 T:1387866416   ERROR: Error loading Settings /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.subscene/resources/settings.xml
20:44:45 T:1387866416   ERROR: Error loading addon settings to special://profile/addon_data/service.subtitles.opensubtitles/settings.xml
20:45:49 T:1387866416   ERROR: Error loading addon settings to special://profile/addon_data/service.subtitles.podnapisi/settings.xml
20:45:56 T:1387866416   ERROR: Error loading Settings /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/service.subtitles.subscene/resources/settings.xml
20:46:02 T:1387866416   ERROR: Error loading addon settings to special://profile/addon_data/service.subtitles.podnapisi/settings.xml

**Comment by babaloui** [comment]
Was able to solve it with a factory reset.
