### ISSUE TITLE
Tweakers.net addon broken only on SPMC

### ISSUE THREAD

**Issue by DragonFlye** [koying/SPMC#390]
While there have been some recent changes (and fixes) with this popular Dutch add-on (now on 1.1.5, however the log refers to 1.1.4) it does not seem to work on SPMC anymore. Tried two default installs:
- SPMC 1.6.0.4
- Krypton Nightly

The addon requires script.module.beautifulsoup and script.module.requests and does work on Krypton (Android/PC) and PC versions of Jarvis (only tested those)

This is the crucial error info:

```
16:39:57 T:1393314096   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.tweakers/)
16:39:57 T:1393314096   DEBUG:   ParentPath = [addons://sources/video]
16:39:57 T:1418717488   DEBUG: bool XFILE::CPluginDirectory::StartScript(const string&, bool) - calling plugin Tweakers('plugin://plugin.video.tweakers/','1','')
16:39:57 T:1418717488   DEBUG: bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - waiting on the Tweakers (id=0) plugin...
16:39:57 T:1434433840   DEBUG: Thread LanguageInvoker start, auto delete: false
16:39:57 T:1434433840    INFO: initializing python engine.
16:39:57 T:1434433840   DEBUG: CPythonInvoker(0, /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py): start processing
16:39:57 T:1434433840   DEBUG: -->Python Interpreter Initialized<--
16:39:57 T:1434433840   DEBUG: CPythonInvoker(0, /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py): the source file to load is "/sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py"
16:39:57 T:1434433840   DEBUG: CPythonInvoker(0, /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py): setting the Python path to /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers:/sdcard/InternalStorage/Kodi/.spmc/addons/script.module.beautifulsoup/lib:/sdcard/InternalStorage/Kodi/.spmc/addons/script.module.requests/lib:/:/data/app/com.semperpax.spmc16-1/base.apk/assets/python2.6/lib/python26.zip:/data/app/com.semperpax.spmc16-1/base.apk/assets/python2.6/lib/python2.6:/data/app/com.semperpax.spmc16-1/base.apk/assets/python2.6/lib/python2.6/plat-linux4:/data/app/com.semperpax.spmc16-1/base.apk/assets/python2.6/lib/python2.6/lib-tk:/data/app/com.semperpax.spmc16-1/base.apk/assets/python2.6/lib/python2.6/lib-old:/data/app/com.semperpax.spmc16-1/base.apk/assets/python2.6/lib/python2.6/lib-dynload
16:39:57 T:1434433840   DEBUG: CPythonInvoker(0, /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py): entering source directory /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers
16:39:57 T:1434433840   DEBUG: CPythonInvoker(0, /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py): instantiating addon using automatically obtained id of "plugin.video.tweakers" dependent on version 2.14.0 of the xbmc.python api
16:39:57 T:1434433840   DEBUG: [ADDON] plugin.video.tweakers, Python Version 2.6.5 (r265:79063, Jul 21 2016, 12:14:43) 
                                            [GCC 4.8]
16:39:57 T:1434433840   DEBUG: [ADDON] plugin.video.tweakers v1.1.4 (2016-07-10) is starting, ARGV = ['plugin://plugin.video.tweakers/', '1', '']
16:39:58 T:1434433840   DEBUG: [ADDON] plugin.video.tweakers v1.1.4 (2016-07-10) debug mode, ARGV = ['plugin://plugin.video.tweakers/', '1', ''], File = /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/resources/lib/tweakers_list.pyo
16:39:58 T:1434433840   DEBUG: POParser: loaded 22 strings from file /sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/resources/language/English/strings.po
16:39:58 T:1434433840   DEBUG: [ADDON] plugin.video.tweakers v1.1.4 (2016-07-10) debug mode, self.video_list_page_url = https://tweakers.net/video/zoeken/?page=001
16:39:58 T:1434433840   DEBUG: [ADDON] plugin.video.tweakers v1.1.4 (2016-07-10) debug mode, self.next_url = https://tweakers.net/video/zoeken/?page=002
16:39:58 T:1434433840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'captureWarnings'
                                            Traceback (most recent call last):
                                              File "/sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/addon.py", line 46, in <module>
                                                plugin.Main()
                                              File "/sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/resources/lib/tweakers_list.py", line 76, in __init__
                                                self.getVideos()
                                              File "/sdcard/InternalStorage/Kodi/.spmc/addons/plugin.video.tweakers/resources/lib/tweakers_list.py", line 100, in getVideos
                                                logging.captureWarnings(True)
                                            AttributeError: 'module' object has no attribute 'captureWarnings'
                                            -->End of Python script error report<--
16:39:58 T:1434433840    INFO: Python script stopped
16:39:58 T:1434433840   DEBUG: Thread LanguageInvoker 1434433840 terminating
16:39:58 T:1418717488   DEBUG:  bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - plugin exited prematurely - terminating
16:39:58 T:1393314096   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.tweakers/
16:39:58 T:1393314096   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tweakers/) failed
```

**Comment by DragonFlye** [comment]
Forgot to mention: Not working on the Shield TV/SPMC

**Comment by DragonFlye** [comment]
Can this be confirmed by a developer. P.S. Also broken on RemixOS when using SPMC.
