### ISSUE TITLE
Crash Shield TV

### ISSUE THREAD

**Issue by beschoenen** [koying/SPMC#469]
My Shield TV just crashed, and I think it has to do with SPMC.

```
--------- beginning of crash
09-09 02:12:24.988  1275  1275 E AndroidRuntime: FATAL EXCEPTION: main
09-09 02:12:24.988  1275  1275 E AndroidRuntime: Process: com.nvidia.osc, PID: 1275
09-09 02:12:24.988  1275  1275 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.nvidia.osc.UIOverlay.getView(UIOverlay.java:357)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.nvidia.osc.GamecastOverlay.onBack(GamecastOverlay.java:140)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.nvidia.osc.UIOverlay.back(UIOverlay.java:258)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.nvidia.osc.UIOverlay.dispatchKeyEvent(UIOverlay.java:293)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.nvidia.osc.UIOverlay$3.dispatchKeyEvent(UIOverlay.java:436)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4273)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4235)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3931)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3988)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3964)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4125)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2264)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1885)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1876)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2241)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.os.MessageQueue.nativePollOnce(Native Method)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.os.MessageQueue.next(MessageQueue.java:323)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:135)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5482)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-09 02:12:24.988  1275  1275 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

SPMC had been building up a huge list of recommendations in the Leanback launcher, literally hundreds, Most of them had images from a thumbnail which I think weren't bigger than 50x50 pixels.
I've scrolled through them a couple of times, only this time, it crashed while doing that, not sure why, but I hope the log might give you more insight.

**Comment by koying** [comment]
Yeah, I've seen this happen as well, but cannot see the pattern.

I thought it was somehow due to me closing and opening SPMC often, for tests.
Would that behaviour apply to you?

**Comment by beschoenen** [comment]
Actually, no. I always have SPMC open because it's the only program I use.
