### ISSUE TITLE
Corrupted storage file (Krypton 20170730: Alpha 8)

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#989]
Upgrading to the Alpha 8 (SPMC-17.4a8-spmc-d838f5c-armeabi-v7a) from Alpha 3 (SPMC-spmc-krypton-3295bca-armeabi-v7a) causes a "Corrupted storage" error with some addons which use xbmcswift2.

Downgrading to Alpha 3 and the issue disappears. 

**plugin.video.itunes_podcasts**

```
10:08:54.690 T:18446744072232093984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Corrupted storage file at /storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/userdata/addon_data/plugin.video.itunes_podcasts/.storage/my_podcasts.json
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.itunes_podcasts/addon.py", line 26, in <module>
                                                my_podcasts = plugin.get_storage('my_podcasts.json', file_format='json')
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 151, in get_storage
                                                raise Exception('Corrupted storage file at %s' % filename)
                                            Exception: Corrupted storage file at /storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/userdata/addon_data/plugin.video.itunes_podcasts/.storage/my_podcasts.json
                                            -->End of Python script error report<--
10:08:54.706 T:1634380064    INFO: Loading skin file: DialogNotification.xml, load type: LOAD_ON_GUI_INIT
10:08:54.709 T:1634380064   ERROR: unable to load:/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/skin.eminence.2.mod/16x9/DialogNotification.xml, Line 68
                                            Error reading end tag.
10:08:54.709 T:1634380064   DEBUG: Load DialogNotification.xml: 3.68ms
10:08:54.709 T:1634380064   DEBUG: Alloc resources: 3.79ms  (3.79 ms skin load)
```
**plugin.audio.shoutcast**

```
10:08:48.573 T:18446744072221632800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Corrupted storage file at /storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/userdata/addon_data/plugin.audio.shoutcast/.storage/my_stations.json
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.audio.shoutcast/addon.py", line 25, in <module>
                                                my_stations = plugin.get_storage('my_stations.json', file_format='json')
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 151, in get_storage
                                                raise Exception('Corrupted storage file at %s' % filename)
                                            Exception: Corrupted storage file at /storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/userdata/addon_data/plugin.audio.shoutcast/.storage/my_stations.json
                                            -->End of Python script error report<--
10:08:48.578 T:1634380064    INFO: Loading skin file: DialogNotification.xml, load type: LOAD_ON_GUI_INIT
10:08:48.586 T:1634380064   ERROR: unable to load:/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/skin.eminence.2.mod/16x9/DialogNotification.xml, Line 68
                                            Error reading end tag.
10:08:48.586 T:1634380064   DEBUG: Load DialogNotification.xml: 8.67ms
```

**Comment by koying** [comment]
Will be fixed in next alpha
